travis:
  secure:
    BINSTAR_TOKEN: xIiX3BRw9tEs+el9RYYYl/jcRZYpI9fOWXanKhSi1Bo0htOaPp1S2pbxl2pZX7twSWWgnj3bwp9/bgf2aQtG7/9qbMu7qPh0FBa68UEuYPhYI0zq8eAvSTCC1o6GfPwi6eDGmtjA7jIb8LAUUo2PP8o3bX+hj6FFbq1EzUUO+Uf1BokHRF6PLBEgixsfIrRXNdvUYgGJN2dtMgd9CuuntKdRgyvACvvyiHruFq6g3oUSMYEroBvsI/KXrWzEDhxovJC/MkQB6kvAeqh9MnfEQggTGhYdMW8JF2qHrO4R9Gn4fwReEC9O6zU0RzwwwJ9vzaeibT7gCtVGL5eW0ouS9BqRVT1FmgIH+ErFty9VMLi34lRMcPCu5akVyGSaLOmLQS0xMBGgm1JOya04r7WTVbgtpnaBPP1bq0mHh0SZCBqCOBMUaE98sRH9eOs4XsT2zVdnqSdZFdO8xSx8cifbJeS4bDCribRnZH/Nznp/2Hr9I4eG+XMQ5iI1P1ngWVqHVoN8mWoCfYplaP00a9amOf8m9bX00fS+MeVngzpl4LXqCmXo22v9PKrRcFxj80itgGFh9K08FNPw+zX4y5D3DK9iyxHeFlzw8/hzwPtPrfOs179Cu9XaHt8HRVBbgW6kVqIqg0EAHosw2HIryccyX2raaeGJM4QDiXqHydve6k4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
