appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JbLBpj5bDhrgfhhVDrNiKTqgM6wQHSP41GT0kvEwdgVpiJizZ85xbOs8wxH8sSOP4G4zahKOysv5Lv822Yb2LDA0thy9IJUN9tmk9Pm3+bOSDtojygQaoGeD5olIQp9QumN1jWrGZKDAtMq/gkMJpKSplQfWZbCrwCl3xSONsSGha9RHTB5eOmY4SuCaRfTlmjHVNXUONBiwC6SK68R0oxQBY5dAqkLdufdcUp4B/QzQu+4CQ3vjrqPt32AsnY/f40prC309n92PiIbHR4+fhwpQj2ymbZiI3E9hnBshSN5huANECDCMCh9xW3mcqPMvJhsWbKE6AQZ+0midR8yqDjUPmQoirGx5XYg8EWON8OYDOn3pASS8vDDyazlKZw5gOmrCDC9iVwtVn9o+aHZEIuR2OMyP6SKg9dX02MF4r2XWLPvyqtw7cOVtbrvDi6ehMgKT8PvGLFKSENbXfgqD3/a/sC4ZIhkFyPbq51r4RUmOPLx5J7ZyO+OLRp/d6KRUklpeOa2FNOmAT8OTTwS2ELim53zUSkXpvqwGQ/C6wy3fLc+IJUsV8FNbIYwJ4CMLKAEMIhe8cVmfIvUyBjWh7tnLelgb7oucoZbpFjDRd6O8h6242b6D4jCwGsTiYEpe48U7mxw1e6cnqEOZkI3fe+vCouXNmMZ1o0nAdui/1Es=}
